### ISSUE TITLE
Use of "parameters" for interface selection

### ISSUE THREAD

**Issue by mjkoster** [openconnectivityfoundation/raml2doc#2]
I don't think parameters can be used to differentiate between for example GET responses on the same resource using different interfaces.

This is just repeating a broken pattern from RAML where we can only define one GET for each resource with one interface parameter

We should translate different interfaces into URIs with query parameters if that is going to be the pattern, e.g.

/temperatureURI?if=oic.if.a
...definitions for actuator payload

/temperatureURI?if=oic.if.r
...definitions for read-only payload

and so on...

**Comment by WAvdBeek** [comment]
correct.

**Comment by WAvdBeek** [comment]
no tool impact
